Add logging to install script

diff --git a/snap/hooks/install b/snap/hooks/install
--- a/snap/hooks/install
+++ b/snap/hooks/install
@@ -9,12 +9,19 @@ tmp_dir="$SNAP_COMMON/pip-install"
 install_dir="$SNAP_DATA/python-packages"
 torch_url=https://download.pytorch.org/whl/torch_stable.html
 
+log_file="$SNAP_COMMON/install.log"
+error_file="$SNAP_COMMON/errors.log"
+
 # Some devices may have a tmpfs filesystem that is too small to unpack torch
 # for installation, which results in "No space left on device" errors.
 export TMPDIR=$tmp_dir
 
-if $SNAP/bin/pip3 install --no-cache-dir --target "$install_dir" --requirement "$SNAP/setup/requirements.$SNAP_ARCH.txt" ; then
-    echo "Python packages installed successfully"
+echo "Running snap install hook..." >$log_file
+
+$SNAP/bin/pip3 install --no-cache-dir --target "$install_dir" --requirement "$SNAP/setup/requirements.$SNAP_ARCH.txt" >>$log_file 2>$error_file
+
+if $? ; then
+    echo "Python packages installed successfully" >>$log_file
 else
-    echo "Python packages were NOT installed"
+    echo "Python packages were NOT installed, check $error_file" >>$log_file
 fi
