Change inference engine to onnx and add segmentation support

diff --git a/snap/hooks/install b/snap/hooks/install
--- a/snap/hooks/install
+++ b/snap/hooks/install
@@ -15,12 +15,12 @@ error_file="$SNAP_COMMON/errors.log"
 # for installation, which results in "No space left on device" errors.
 export TMPDIR="$tmp_dir"
 
-echo "Running snap install hook..." >$log_file
-
-"$SNAP/bin/python3" -m pip install --no-cache-dir --prefix "$install_dir" --requirement "$SNAP/setup/requirements.$SNAP_ARCH.txt" >>"$log_file" 2>"$error_file"
-
-if [ $? -eq 0 ]; then
-    echo "Python packages installed successfully" >>"$log_file"
-else
-    echo "Python packages were NOT installed, check $error_file" >>"$log_file"
-fi
+#echo "Running snap install hook..." >$log_file
+#
+#"$SNAP/bin/python3" -m pip install --no-cache-dir --prefix "$install_dir" --requirement "$SNAP/setup/requirements.$SNAP_ARCH.txt" >>"$log_file" 2>"$error_file"
+#
+#if [ $? -eq 0 ]; then
+#    echo "Python packages installed successfully" >>"$log_file"
+#else
+#    echo "Python packages were NOT installed, check $error_file" >>"$log_file"
+#fi
